#!/usr/bin/env python3
"""Writes the Studio3D / StudioIA symbol as clean vectors: landing/symbol.svg,
landing/favicon.svg, and the inline <symbol id="brand-symbol"> between the
`brand-symbol` markers in landing/*.html (that copy colors each piece with a
CSS variable, so the page can recolor it for dark mode and the watermark).

The brand manual (Studio3D visual identity, 2021) only ships the symbol as
raster logos (brand/studio3d/*.png). This rebuilds it from measurements of
those files: four identical "D" pieces (220 x 110, one rounded long side) and a
teal corner piece, in the manual's five colors. The rounded sides are the
cubic curves fitted to the logo's outline (under 1.3px RMS at 347px wide), so
the organic "D" shape is kept while edges stay crisp at favicon size.

Usage:
  python3 scripts/brand-assets/build-symbol.py
"""

import re
from pathlib import Path

# Manual colors (Cores page): Natural Black, 173U, 329U, 1805U, 282U.
BLACK, ORANGE, TEAL, RED, NAVY = "#2A2929", "#C25939", "#18726E", "#A53B3F", "#263E5A"
# CSS variable per piece in the inline copy (falls back to the manual color).
VARS = {BLACK: "--sym-black", ORANGE: "--sym-orange", TEAL: "--sym-teal", RED: "--sym-red", NAVY: "--sym-navy"}

# The shared "D" profile. Along the rounded side, each half is a cubic from the
# end edge (where the corner starts, R in from the side) to the side's middle.
D_LEN, D_R, D_A, D_C = 220, 48, 40, 80

# Pieces as (x0, y0, x1, y1, rounded side, color), in the logo's 348 x 354 grid.
PIECES = [
    (0, 14, 110, 234, "left", BLACK),
    (120, 1, 340, 111, "top", ORANGE),
    (238, 124, 348, 344, "right", RED),
    (10, 243, 230, 353, "bottom", NAVY),
]

# Teal: square except its top-right corner, a cubic from the top edge (R in from
# the right) to the right edge (H down from the top).
TEAL_RECT = (120, 122, 230, 243)
TEAL_R, TEAL_H, TEAL_A, TEAL_C = 44, 84, 35, 50

VIEW_W, VIEW_H = 348, 354


def fmt(v):
    return f"{v:g}"


def d_piece(x0, y0, x1, y1, side):
    """Path for a rectangle whose `side` is the rounded long side."""
    half = D_LEN / 2

    # Map (along, depth) on the rounded side to x/y. `along` runs from the start
    # end edge; `depth` is measured inward from the rounded side's bound.
    def pt(along, depth):
        if side == "left":
            return x0 + depth, y0 + along
        if side == "right":
            return x1 - depth, y0 + along
        if side == "top":
            return x0 + along, y0 + depth
        return x0 + along, y1 - depth  # bottom

    def p(along, depth):
        x, y = pt(along, depth)
        return f"{fmt(x)} {fmt(y)}"

    L = D_LEN
    # Far corners (the flat side), in the order that closes the path.
    far = {
        "left": [(x1, y1), (x1, y0)],
        "right": [(x0, y1), (x0, y0)],
        "top": [(x1, y1), (x0, y1)],
        "bottom": [(x1, y0), (x0, y0)],
    }[side]
    return (
        f"M{p(0, D_R)}"
        f"C{p(0, D_R - D_A)} {p(half - D_C, 0)} {p(half, 0)}"
        f"C{p(half + D_C, 0)} {p(L, D_R - D_A)} {p(L, D_R)}"
        f"L{fmt(far[0][0])} {fmt(far[0][1])}"
        f"L{fmt(far[1][0])} {fmt(far[1][1])}Z"
    )


def teal_piece():
    x0, y0, x1, y1 = TEAL_RECT
    return (
        f"M{fmt(x0)} {fmt(y0)}"
        f"L{fmt(x1 - TEAL_R)} {fmt(y0)}"
        f"C{fmt(x1 - TEAL_R + TEAL_A)} {fmt(y0)} {fmt(x1)} {fmt(y0 + TEAL_H - TEAL_C)} {fmt(x1)} {fmt(y0 + TEAL_H)}"
        f"L{fmt(x1)} {fmt(y1)}L{fmt(x0)} {fmt(y1)}Z"
    )


def pieces():
    yield TEAL, teal_piece()
    for x0, y0, x1, y1, side, color in PIECES:
        yield color, d_piece(x0, y0, x1, y1, side)


def main():
    landing = Path(__file__).resolve().parents[2] / "landing"

    paths = [f'  <path fill="{color}" d="{d}"/>' for color, d in pieces()]
    svg = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VIEW_W} {VIEW_H}">\n'
        "  <!-- Generated by scripts/brand-assets/build-symbol.py - edit that, not this. -->\n"
        + "\n".join(paths)
        + "\n</svg>\n"
    )
    (landing / "symbol.svg").write_text(svg)
    print("Wrote landing/symbol.svg")

    # Favicon: the symbol, with the manual's dark-ground rule (the black piece
    # turns light) for browsers whose tab strip is dark.
    fav_paths = []
    for color, d in pieces():
        cls = ' class="k"' if color == BLACK else ""
        fav_paths.append(f'  <path{cls} fill="{color}" d="{d}"/>')
    favicon = (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {VIEW_W} {VIEW_H}">\n'
        "  <!-- Generated by scripts/brand-assets/build-symbol.py - edit that, not this. -->\n"
        "  <style>@media (prefers-color-scheme: dark) { .k { fill: #f3f1f0; } }</style>\n"
        + "\n".join(fav_paths)
        + "\n</svg>\n"
    )
    (landing / "favicon.svg").write_text(favicon)
    print("Wrote landing/favicon.svg")

    inline = "\n".join(
        f'        <path style="fill: var({VARS[color]}, {color})" d="{d}" />' for color, d in pieces()
    )
    block = (
        "<!-- brand-symbol:start (generated by scripts/brand-assets/build-symbol.py) -->\n"
        '    <svg width="0" height="0" style="position: absolute" aria-hidden="true" focusable="false">\n'
        f'      <symbol id="brand-symbol" viewBox="0 0 {VIEW_W} {VIEW_H}">\n{inline}\n      </symbol>\n'
        "    </svg>\n"
        "    <!-- brand-symbol:end -->"
    )
    marker = re.compile(r"<!-- brand-symbol:start.*?<!-- brand-symbol:end -->", re.S)
    # Asset sources (og-image.html) and the landing template use the inline copy too.
    scripts = Path(__file__).resolve().parents[1]
    extra = [*scripts.glob("brand-assets/*.html"), *scripts.glob("landing/*.html")]
    for page in sorted([*landing.glob("**/*.html"), *extra]):
        text = page.read_text()
        if marker.search(text):
            page.write_text(marker.sub(lambda _: block, text))
            print(f"Updated the inline symbol in {page.relative_to(landing.parent)}")


if __name__ == "__main__":
    main()
