#!/usr/bin/env python3
"""Writes the Studio3D tile texture as vectors: landing/texture.svg (full color)
and landing/texture-tint.svg (the manual's light tints, for quiet backgrounds).

The brand manual ships the texture only as a raster (brand/studio3d/texture.png).
Each of its four colors is separated into a mask and traced with potrace, so the
texture stays sharp at any band size. The tint version is the same shapes with
each color swapped for its manual tint (Cores page, second row).

Usage:
  python3 scripts/brand-assets/build-texture.py
Needs: potrace on PATH (e.g. `nix shell nixpkgs#potrace`), python3 with Pillow.
"""

import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "brand" / "studio3d" / "texture.png"

# (full color, tint) per manual color. The texture uses the four brand colors,
# not the black.
COLORS = {
    "orange": ((194, 89, 57), "#F6E6E1"),
    "teal": ((24, 114, 110), "#DDEAE9"),
    "red": ((165, 59, 63), "#F2E2E2"),
    "navy": ((38, 62, 90), "#DFE2E6"),
}
UPSCALE = 2  # trace at 2x for smoother curves


def hexcolor(rgb):
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def main():
    im = Image.open(SOURCE).convert("RGBA")
    alpha = im.split()[3].point(lambda v: 255 if v > 128 else 0)
    im = im.crop(alpha.getbbox())
    big = im.resize((im.width * UPSCALE, im.height * UPSCALE), Image.LANCZOS)
    w, h = big.size
    px = big.load()

    masks = {name: Image.new("1", big.size, 1) for name in COLORS}
    mpx = {name: m.load() for name, m in masks.items()}
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a < 128 or (r > 225 and g > 225 and b > 225):
                continue  # background and the white gaps between pieces
            name = min(
                COLORS,
                key=lambda n: sum((c - v) ** 2 for c, v in zip(COLORS[n][0], (r, g, b))),
            )
            mpx[name][x, y] = 0

    paths = {}
    with tempfile.TemporaryDirectory() as tmp:
        for name, mask in masks.items():
            pbm, svg = Path(tmp) / f"{name}.pbm", Path(tmp) / f"{name}.svg"
            mask.save(pbm)
            subprocess.run(
                ["potrace", "-s", "--flat", "-t", "60", "-a", "1.1", "-O", "1.5", "-u", "1",
                 str(pbm), "-o", str(svg)],
                check=True,
            )
            text = svg.read_text()
            transform = re.search(r'<g transform="([^"]+)"', text).group(1)
            d = " ".join(re.findall(r'<path d="([^"]+)"', text))
            paths[name] = (transform, d)

    for out_name, pick in (("texture.svg", 0), ("texture-tint.svg", 1)):
        body = "\n".join(
            f'  <g transform="{paths[n][0]}" fill="{hexcolor(COLORS[n][0]) if pick == 0 else COLORS[n][1]}">'
            f'<path d="{paths[n][1]}"/></g>'
            for n in COLORS
        )
        svg = (
            f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" preserveAspectRatio="xMidYMid slice">\n'
            "  <!-- Generated by scripts/brand-assets/build-texture.py - edit that, not this. -->\n"
            f"{body}\n</svg>\n"
        )
        (ROOT / "landing" / out_name).write_text(svg)
        print(f"Wrote landing/{out_name} ({len(svg) // 1024} KB)")


if __name__ == "__main__":
    main()
