#!/usr/bin/env python3
"""Builds the landing page in each language from one template.

  scripts/landing/index.html          the template ({{key}} placeholders)
  scripts/landing/strings/<lang>.json the text for each language
    -> landing/index.html             English, at /
    -> landing/pt-br/index.html       Portuguese (Brazil), at /pt-br

Every language must define exactly the keys English defines; the build fails
on a missing, extra or unknown key, so the pages cannot drift apart. String
values may contain inline HTML (e.g. <strong>, &nbsp;) and are inserted as-is.

Usage:
  python3 scripts/landing/build.py
Run it after editing the template or any strings file, and commit the output.
"""

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SITE = "https://render-ai-studio.web.app"

# code -> page settings. `path` is the public URL path, `out` the file under landing/.
LANGS = {
    "en": {"path": "/", "out": "index.html", "og_locale": "en_US", "short": "EN", "name": "View in English"},
    "pt-BR": {"path": "/pt-br", "out": "pt-br/index.html", "og_locale": "pt_BR", "short": "PT", "name": "Ver em português"},
}
DEFAULT = "en"

PLACEHOLDER = re.compile(r"\{\{([\w.]+)\}\}")


def alternates():
    lines = [
        f'    <link rel="alternate" hreflang="{code}" href="{SITE}{cfg["path"]}" />'
        for code, cfg in LANGS.items()
    ]
    lines.append(f'    <link rel="alternate" hreflang="x-default" href="{SITE}{LANGS[DEFAULT]["path"]}" />')
    return "\n".join(lines)


def page_values(code):
    cfg = LANGS[code]
    # The switch links to the other language (two languages today).
    other = next(c for c in LANGS if c != code)
    other_cfg = LANGS[other]
    return {
        "lang": code,
        "url": f"{SITE}{cfg['path']}",
        "alternates": alternates(),
        "ogImage": f"{SITE}/og-image{'' if code == DEFAULT else '-' + code.lower()}.png",
        "ogLocale": cfg["og_locale"],
        "ogLocaleAlt": other_cfg["og_locale"],
        "switch.href": other_cfg["path"],
        "switch.hreflang": other,
        "switch.label": other_cfg["name"],
        "switch.text": other_cfg["short"],
    }


def main():
    template = (HERE / "index.html").read_text()
    strings = {code: json.loads((HERE / "strings" / f"{code}.json").read_text()) for code in LANGS}

    base_keys = set(strings[DEFAULT])
    for code, table in strings.items():
        missing, extra = base_keys - set(table), set(table) - base_keys
        if missing or extra:
            raise SystemExit(f"{code}.json: missing {sorted(missing)}, extra {sorted(extra)}")

    for code, cfg in LANGS.items():
        values = {**strings[code], **page_values(code)}

        def fill(match):
            key = match.group(1)
            if key not in values:
                raise SystemExit(f"template uses unknown key {{{{{key}}}}}")
            value = values[key]
            return value

        html = PLACEHOLDER.sub(fill, template)
        html = html.replace(
            "<!doctype html>\n",
            "<!doctype html>\n<!-- Generated by scripts/landing/build.py - edit the template and strings there. -->\n",
            1,
        )
        out = ROOT / "landing" / cfg["out"]
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html)
        print(f"Wrote landing/{cfg['out']}")

    unused = base_keys - set(PLACEHOLDER.findall(template))
    if unused:
        raise SystemExit(f"strings not used by the template: {sorted(unused)}")


if __name__ == "__main__":
    main()
